logLevel = "INFO"
checkNewVersion = false
defaultEntryPoints = ["http", "https"]

[web]
  address = ":8080"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    # [entryPoints.http.redirect]
      # entryPoint = "https"
    [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]

[acme]
  email = "charlesnowow@gmail.com"
  entryPoint = "https"
  OnHostRule = false
  storage = "acme.json"
  acmeLogging = true
  # caServer = "https://acme-staging.api.letsencrypt.org/directory"
  # caServer = "https://acme-v02.api.letsencrypt.org/directory"
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [acme.httpChallenge]
    entryPoint = "http"
  [acme.dnsChallenge]
    provider = "digitalocean"
    delayBeforeCheck = 0
  [[acme.domains]]
    main = "*.chno.xyz" #this one gets the certificate
    sans = ["chno.xyz"]
  # [acme.httpChallenge]
    # entryPoint = "http"


[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedbydefault = false
  swarmmode = true
