logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[web]
  address = ":8080"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    # [entryPoints.http.redirect]
      # entryPoint = "https"
    [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]

[acme]
  email = "charlesnowow@gmail.com"
  entryPoint = "https"
  storage = "acme.json"
  acmeLogging = true
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [acme.dnsChallenge]
    provider = "digitalocean"
  [[acme.domains]]
    main = "*.chno.xyz"
    sans = ["chno.xyz"]


[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedbydefault = false
  swarmmode = true
